name : Docker Image build and push
on:
  push:
    tags:
      - v1.**
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      input: environment_variable
      username: ${{ secrets.USERNAME }}
      password: ${{ secrets.PASSWORD }}      
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to JFrog
        uses: docker/login-action@v1
        with:
          registry: sdai.jfrog.io
          username: username
          password: password
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: user/app:latest
